export type InterviewQuestion = {
  id: number
  question: string
  difficulty: "초급" | "중급" | "고급"
}

// Types exported for client-side usage
export type QuestionsByCategory = Record<string, InterviewQuestion[]>

export const questionsByCategory: QuestionsByCategory = {
  공통질문: [
    { id: 1, question: "1분 자기소개를 해주세요.", difficulty: "초급" },
    { id: 2, question: "우리 회사를 지원하게 된 구체적인 동기는 무엇인가요?", difficulty: "초급" },
    { id: 3, question: "본인의 성격 중 기획 업무에 가장 도움이 되는 장점은 무엇인가요?", difficulty: "초급" },
    { id: 4, question: "반대로 업무 시 치명적일 수 있는 단점과 이를 보완할 방법은요?", difficulty: "초급" },
    { id: 5, question: "입사 후 1년 뒤, 3년 뒤, 5년 뒤 본인의 모습을 그려본다면?", difficulty: "초급" },
    { id: 6, question: "가장 기억에 남는 실패 경험과 그로부터 배운 점은 무엇인가요?", difficulty: "중급" },
    { id: 7, question: "개발자(프로그래머)와 기획 내용으로 갈등이 생겼을 때 어떻게 해결하나요?", difficulty: "중급" },
    {
      id: 8,
      question: "아트 담당자가 기획 의도와 다른 결과물을 가져왔을 때 어떻게 피드백하시겠습니까?",
      difficulty: "중급",
    },
    {
      id: 9,
      question: "상사가 본인의 생각과 완전히 다른, 비효율적인 지시를 내린다면 어떻게 할까요?",
      difficulty: "고급",
    },
    { id: 10, question: "팀 프로젝트에서 '무임승차'하는 동료를 대처해 본 경험이 있나요?", difficulty: "중급" },
    {
      id: 11,
      question: "마감 일정이 3일 남았는데 기획의 치명적인 결함을 발견했다면 어떻게 하시겠습니까?",
      difficulty: "고급",
    },
    { id: 12, question: "본인이 생각하는 '좋은 게임'의 정의는 무엇인가요?", difficulty: "중급" },
    { id: 13, question: "평소 스트레스 관리는 어떻게 하시나요?", difficulty: "초급" },
    {
      id: 14,
      question: "최근 즐겨 하는 게임은 무엇이며, 그 게임의 성공 요인은 무엇이라 생각하나요?",
      difficulty: "중급",
    },
    {
      id: 15,
      question: "플레이하다가 중간에 그만둔 게임이 있다면, 결정적인 이탈 사유는 무엇이었나요?",
      difficulty: "중급",
    },
    { id: 16, question: "본인이 리더라면 팀원들에게 어떤 평가를 받는 리더가 되고 싶나요?", difficulty: "중급" },
    { id: 17, question: "우리 회사의 라이브 게임 중 하나를 선택해 개선점을 말해보세요.", difficulty: "고급" },
    { id: 18, question: "게임 기획자가 갖춰야 할 필수 역량 3가지를 꼽는다면?", difficulty: "중급" },
    { id: 19, question: "최근 업계의 트렌드 중 본인이 가장 주목하는 키워드는 무엇인가요?", difficulty: "중급" },
    { id: 20, question: "생성형 AI가 기획자의 업무를 어디까지 대체할 수 있다고 생각하나요?", difficulty: "고급" },
    {
      id: 21,
      question: "본인의 기획서가 반려되었을 때, 멘탈을 회복하는 본인만의 노하우가 있나요?",
      difficulty: "중급",
    },
    { id: 22, question: "야근이나 주말 출근 등 업무 강도가 높은 상황에 대해 어떻게 생각하시나요?", difficulty: "중급" },
    { id: 23, question: "본인은 리더형에 가깝나요, 팔로워형에 가깝나요?", difficulty: "초급" },
    { id: 24, question: "게임 외에 영감을 얻는 취미나 활동이 있나요? (영화, 독서, 여행 등)", difficulty: "초급" },
    { id: 25, question: "본인의 포트폴리오에서 가장 자신 있는 프로젝트 하나를 소개해 주세요.", difficulty: "중급" },
    { id: 26, question: "해당 프로젝트에서 본인의 기여도는 몇 퍼센트 정도라고 생각하나요?", difficulty: "중급" },
    { id: 27, question: "팀원들과 의견을 조율할 때 본인만의 설득 스킬이 있나요?", difficulty: "중급" },
    { id: 28, question: "본인의 가치관과 회사의 비전이 충돌한다면 어떻게 하시겠습니까?", difficulty: "고급" },
    { id: 29, question: "만약 이번 면접에서 떨어진다면 그 이유는 무엇일 것이라 예상하나요?", difficulty: "고급" },
    { id: 30, question: "마지막으로 면접관에게 하고 싶은 질문이 있나요?", difficulty: "초급" },
    // 뉘앙스 변형 및 상황 추가 (31-100)
    { id: 31, question: "30초 자기소개를 간결하게 해주세요.", difficulty: "초급" },
    { id: 32, question: "자기소개 시 본인의 강점을 어떻게 어필하시겠습니까?", difficulty: "초급" },
    { id: 33, question: "우리 회사의 게임을 플레이해본 경험이 있나요?", difficulty: "초급" },
    { id: 34, question: "경쟁사가 아닌 우리 회사를 선택한 이유는 무엇인가요?", difficulty: "중급" },
    { id: 35, question: "본인의 단점이 팀워크에 어떤 영향을 줄 수 있나요?", difficulty: "중급" },
    { id: 36, question: "입사 후 첫 1개월 동안 무엇을 배우고 싶으신가요?", difficulty: "초급" },
    { id: 37, question: "10년 후 본인은 어떤 기획자가 되어있을까요?", difficulty: "중급" },
    { id: 38, question: "가장 큰 성공 경험과 그 이유는 무엇인가요?", difficulty: "중급" },
    {
      id: 39,
      question: "프로그래머가 일정 지연으로 인해 기능 구현이 어렵다고 할 때 어떻게 대응하나요?",
      difficulty: "고급",
    },
    { id: 40, question: "아트 담당자가 일정을 못 맞출 것 같다고 미리 말한다면?", difficulty: "중급" },
    { id: 41, question: "상사의 지시가 유저에게 해가 된다고 확신할 때의 대처법은?", difficulty: "고급" },
    { id: 42, question: "팀원이 업무 중 연락 두절일 때 어떻게 하시겠습니까?", difficulty: "고급" },
    { id: 43, question: "마감 하루 전 큰 버그가 발견되었다면?", difficulty: "고급" },
    { id: 44, question: "본인이 생각하는 '재미없는 게임'은 어떤 게임인가요?", difficulty: "중급" },
    { id: 45, question: "업무 스트레스가 최고조에 달했을 때의 대처법은?", difficulty: "중급" },
    { id: 46, question: "최근 1년 이내 플레이한 게임 중 가장 인상 깊은 게임은?", difficulty: "초급" },
    { id: 47, question: "게임을 10분만 플레이하고 삭제한 경험이 있다면 그 이유는?", difficulty: "중급" },
    { id: 48, question: "본인이 팔로워라면 어떤 리더를 따르고 싶나요?", difficulty: "초급" },
    { id: 49, question: "우리 회사 게임의 가장 큰 문제점은 무엇이라고 생각하나요?", difficulty: "고급" },
    { id: 50, question: "게임 기획자에게 가장 불필요한 역량은 무엇일까요?", difficulty: "중급" },
    { id: 51, question: "메타버스 트렌드에 대해 어떻게 생각하시나요?", difficulty: "중급" },
    { id: 52, question: "AI가 기획자를 완전히 대체할 수 있다고 생각하나요?", difficulty: "고급" },
    { id: 53, question: "기획서가 3번 연속 반려되었다면 어떻게 하시겠습니까?", difficulty: "고급" },
    { id: 54, question: "크런치 타임(집중 야근 기간)에 대한 본인의 생각은?", difficulty: "중급" },
    { id: 55, question: "리더와 팔로워 중 어느 쪽이 더 어렵다고 생각하나요?", difficulty: "중급" },
    { id: 56, question: "최근 본 영화나 드라마에서 게임에 적용하고 싶은 요소가 있나요?", difficulty: "중급" },
    { id: 57, question: "포트폴리오 중 가장 아쉬운 프로젝트와 그 이유는?", difficulty: "중급" },
    { id: 58, question: "팀 프로젝트에서 본인의 역할은 주로 무엇이었나요?", difficulty: "초급" },
    { id: 59, question: "의견 충돌 시 다수결로 결정하는 것에 대해 어떻게 생각하나요?", difficulty: "중급" },
    { id: 60, question: "회사의 수익과 본인의 철학이 충돌한다면?", difficulty: "고급" },
    { id: 61, question: "이번 면접에서 가장 자신 있게 답변한 질문은?", difficulty: "초급" },
    { id: 62, question: "면접관에게 듣고 싶지 않은 피드백이 있다면?", difficulty: "중급" },
    { id: 63, question: "게임 개발 과정에서 가장 중요한 단계는 언제라고 생각하나요?", difficulty: "중급" },
    { id: 64, question: "유저 피드백과 데이터 중 무엇을 더 신뢰하나요?", difficulty: "고급" },
    { id: 65, question: "본인의 기획이 실패했을 때 책임을 어떻게 지시겠습니까?", difficulty: "고급" },
    { id: 66, question: "게임업계의 가장 큰 문제점은 무엇이라고 생각하나요?", difficulty: "중급" },
    { id: 67, question: "좋아하는 게임 장르와 그 이유를 말씀해주세요.", difficulty: "초급" },
    { id: 68, question: "싫어하는 게임 장르가 있다면 그 이유는?", difficulty: "초급" },
    { id: 69, question: "게임 기획자가 코딩을 할 줄 알아야 한다고 생각하나요?", difficulty: "중급" },
    { id: 70, question: "게임 기획자가 그림을 그릴 줄 알아야 한다고 생각하나요?", difficulty: "중급" },
    { id: 71, question: "본인만의 게임 개발 철학이 있다면 무엇인가요?", difficulty: "고급" },
    { id: 72, question: "게임의 그래픽과 재미 중 무엇이 더 중요할까요?", difficulty: "중급" },
    { id: 73, question: "과금 유도가 심한 게임에 대해 어떻게 생각하나요?", difficulty: "중급" },
    { id: 74, question: "게임 내 광고에 대한 본인의 의견은?", difficulty: "중급" },
    { id: 75, question: "e스포츠의 미래에 대해 어떻게 전망하시나요?", difficulty: "중급" },
    { id: 76, question: "모바일 게임과 PC 게임 중 어느 시장이 더 유망할까요?", difficulty: "중급" },
    { id: 77, question: "콘솔 게임 시장의 특징을 설명해주세요.", difficulty: "중급" },
    { id: 78, question: "인디 게임의 성공 요인은 무엇이라고 생각하나요?", difficulty: "중급" },
    { id: 79, question: "AAA 게임과 인디 게임 중 어디서 일하고 싶으신가요?", difficulty: "초급" },
    { id: 80, question: "게임 개발에서 가장 힘든 점은 무엇일까요?", difficulty: "중급" },
    { id: 81, question: "게임 개발에서 가장 보람찬 순간은 언제일까요?", difficulty: "중급" },
    { id: 82, question: "본인의 롤모델 게임 기획자가 있나요?", difficulty: "초급" },
    { id: 83, question: "가장 존경하는 게임 개발사는 어디인가요?", difficulty: "초급" },
    { id: 84, question: "게임 업계에서 10년 뒤에도 살아남으려면 무엇이 필요할까요?", difficulty: "고급" },
    { id: 85, question: "본인의 커리어 목표를 구체적으로 말씀해주세요.", difficulty: "중급" },
    { id: 86, question: "이직을 고려하는 가장 큰 이유는 무엇인가요?", difficulty: "중급" },
    { id: 87, question: "전 회사를 퇴사한 이유를 말씀해주세요.", difficulty: "중급" },
    { id: 88, question: "우리 회사에서 가장 하고 싶은 프로젝트는 무엇인가요?", difficulty: "중급" },
    { id: 89, question: "연봉 협상 시 가장 중요하게 생각하는 것은?", difficulty: "중급" },
    { id: 90, question: "연봉보다 중요한 가치가 있다면 무엇인가요?", difficulty: "중급" },
    { id: 91, question: "재택근무와 사무실 근무 중 선호하는 방식은?", difficulty: "초급" },
    { id: 92, question: "해외 출장이나 지사 파견 기회가 있다면 가시겠습니까?", difficulty: "초급" },
    { id: 93, question: "팀 회식 문화에 대해 어떻게 생각하나요?", difficulty: "초급" },
    { id: 94, question: "회사의 수평적 문화와 수직적 문화 중 선호하는 것은?", difficulty: "중급" },
    { id: 95, question: "동료와의 경쟁과 협력 중 무엇이 더 중요할까요?", difficulty: "중급" },
    { id: 96, question: "실패를 두려워하지 않는 본인만의 방법이 있나요?", difficulty: "중급" },
    { id: 97, question: "게임 업계의 성차별 문제에 대해 어떻게 생각하나요?", difficulty: "고급" },
    { id: 98, question: "게임 개발에서 다양성이 중요한 이유는 무엇일까요?", difficulty: "고급" },
    { id: 99, question: "본인이 우리 회사에 기여할 수 있는 가장 큰 가치는?", difficulty: "고급" },
    { id: 100, question: "5년 후 이 면접을 되돌아본다면 어떤 생각이 들 것 같나요?", difficulty: "고급" },
  ],

  시스템기획: [
    { id: 1, question: "본인이 기획한 시스템 중 가장 논리적으로 완벽했다고 생각하는 것은?", difficulty: "고급" },
    { id: 2, question: "역기획서를 작성해 본 경험이 있나요? 가장 어려웠던 점은 무엇인가요?", difficulty: "중급" },
    {
      id: 3,
      question: "게임 내 경제 인플레이션을 잡기 위한 가장 효과적인 재화 회수처(Sink)는 무엇일까요?",
      difficulty: "고급",
    },
    {
      id: 4,
      question: "강화 시스템에서 유저의 실패 스트레스를 줄이기 위한 보완 장치는 무엇이 있을까요?",
      difficulty: "중급",
    },
    {
      id: 5,
      question: "신규 시스템 기획 시, 기존 시스템과의 충돌(Side Effect)을 어떻게 예측하나요?",
      difficulty: "고급",
    },
    {
      id: 6,
      question: "프로그래머가 이해하기 쉬운 기획서(테이블 정의 등)를 쓰기 위해 신경 쓰는 점은?",
      difficulty: "중급",
    },
    { id: 7, question: "데이터 테이블 구조를 짤 때, 확장성을 고려해 설계해 본 경험이 있나요?", difficulty: "고급" },
    { id: 8, question: "확률형 아이템의 확률을 설정할 때 어떤 기준이나 수식을 사용하나요?", difficulty: "고급" },
    { id: 9, question: "유저들이 시스템의 허점을 이용해 어뷰징을 한다면 어떻게 대처하시겠습니까?", difficulty: "고급" },
    {
      id: 10,
      question: "커뮤니티 반응은 나쁜데 데이터 지표(매출, 리텐션)는 좋은 시스템이 있다면 유지하시겠습니까?",
      difficulty: "고급",
    },
    {
      id: 11,
      question: "길드나 파티 같은 커뮤니티 시스템이 게임 수명에 미치는 영향은 무엇일까요?",
      difficulty: "중급",
    },
    { id: 12, question: "경매장(거래소) 시스템 유무에 따른 게임 경제의 장단점을 비교해 보세요.", difficulty: "고급" },
    { id: 13, question: "업적 시스템이 단순한 숙제가 되지 않고 동기부여가 되게 하려면?", difficulty: "중급" },
    { id: 14, question: "VIP 시스템이나 배틀패스 BM을 설계할 때 가장 중요하게 고려할 점은?", difficulty: "고급" },
    { id: 15, question: "튜토리얼 없이도 시스템을 이해시킬 수 있는 방법이 있을까요?", difficulty: "고급" },
    {
      id: 16,
      question: "게임의 핵심 재미(Core Loop)를 시스템적으로 도식화해서 설명해 줄 수 있나요?",
      difficulty: "고급",
    },
    { id: 17, question: "방치형 요소와 조작형 요소의 밸런스를 어떻게 맞춰야 할까요?", difficulty: "중급" },
    {
      id: 18,
      question: "매칭 시스템(MMR) 기획 시, 대기 시간 단축과 실력 격차 해소 중 무엇이 우선일까요?",
      difficulty: "고급",
    },
    {
      id: 19,
      question: "채팅 시스템에서 욕설이나 비매너 행위를 시스템적으로 제재하는 아이디어가 있나요?",
      difficulty: "중급",
    },
    { id: 20, question: "인벤토리 공간 부족 문제는 과금 요소인가요, 편의성 문제인가요?", difficulty: "중급" },
    { id: 21, question: "제작/크래프팅 시스템에서 재료 수급 난이도 조절은 어떤 기준으로 하나요?", difficulty: "중급" },
    { id: 22, question: "시즌제 게임에서 시즌 초기화 시 유저 반발을 최소화하는 시스템적 보상은?", difficulty: "고급" },
    { id: 23, question: "포트폴리오의 이 시스템은 어떤 게임을 레퍼런스로 삼았나요?", difficulty: "중급" },
    {
      id: 24,
      question: "해당 시스템 구현을 위해 클라이언트/서버 중 어디와 더 긴밀히 소통해야 할까요?",
      difficulty: "고급",
    },
    { id: 25, question: "복잡한 수식을 유저에게 직관적인 UI 수치로 변환해 보여주는 방법은?", difficulty: "중급" },
    { id: 26, question: "랜덤 요소(RNG)가 게임의 재미에 미치는 긍정적/부정적 영향은?", difficulty: "중급" },
    {
      id: 27,
      question: "로그라이크 장르의 '죽음 후 계승' 요소를 RPG에 도입한다면 어떻게 기획하시겠습니까?",
      difficulty: "고급",
    },
    { id: 28, question: "다중 재화(골드, 다이아, 마일리지 등)를 사용하는 이유와 밸런싱 방법은?", difficulty: "중급" },
    { id: 29, question: "이벤트 시스템을 기획할 때, 보상 밸런스는 평소의 몇 배율로 잡나요?", difficulty: "중급" },
    {
      id: 30,
      question: "본인이 생각하는 가장 이상적인 성장 곡선(Level Design 말고 Stat Curve)은 어떤 형태인가요?",
      difficulty: "고급",
    },
    // 뉘앙스 변형 및 상황 추가 (31-100)
    { id: 31, question: "본인이 기획한 시스템 중 가장 실패한 사례는 무엇인가요?", difficulty: "고급" },
    { id: 32, question: "역기획서 작성 시 가장 먼저 분석하는 요소는 무엇인가요?", difficulty: "중급" },
    { id: 33, question: "게임 경제에서 재화 생성(Source)과 소비(Sink)의 적정 비율은?", difficulty: "고급" },
    { id: 34, question: "강화 실패 시 아이템 파괴 시스템에 대해 어떻게 생각하나요?", difficulty: "중급" },
    { id: 35, question: "기존 시스템을 수정할 때 우선순위를 어떻게 정하시나요?", difficulty: "중급" },
    { id: 36, question: "프로그래머가 기획서를 이해 못 한다고 할 때 어떻게 대응하나요?", difficulty: "중급" },
    { id: 37, question: "데이터 테이블에서 하드코딩과 설정값의 경계는 어디인가요?", difficulty: "고급" },
    { id: 38, question: "확률형 뽑기의 천장 시스템을 몇 회로 설정해야 적절할까요?", difficulty: "중급" },
    { id: 39, question: "어뷰징 발견 후 소급 처벌을 할 것인가 경고만 할 것인가?", difficulty: "고급" },
    { id: 40, question: "데이터는 좋지만 평가가 나쁜 시스템을 언제까지 유지하시겠습니까?", difficulty: "고급" },
    { id: 41, question: "길드 시스템에서 길드장의 권한은 어디까지 주어야 할까요?", difficulty: "중급" },
    { id: 42, question: "거래소 시스템에서 시세 조작을 방지하는 방법은?", difficulty: "고급" },
    { id: 43, question: "업적 보상이 너무 좋으면 생기는 문제점은?", difficulty: "중급" },
    { id: 44, question: "무료 배틀패스와 유료 배틀패스의 보상 격차는 어느 정도가 적절한가요?", difficulty: "중급" },
    { id: 45, question: "튜토리얼 스킵 유저를 위한 대안은 무엇인가요?", difficulty: "중급" },
    { id: 46, question: "Core Loop가 약한 게임의 특징은 무엇인가요?", difficulty: "중급" },
    { id: 47, question: "방치형 게임에서 플레이어의 개입이 필요한 시점은?", difficulty: "중급" },
    { id: 48, question: "매칭 시스템에서 승률 50%를 강제로 맞추는 것에 대한 의견은?", difficulty: "고급" },
    { id: 49, question: "채팅 필터링의 과도한 제재가 불편하다는 의견에 대한 대응은?", difficulty: "중급" },
    { id: 50, question: "인벤토리 확장을 과금 상품으로 판매하는 것이 적절한가요?", difficulty: "중급" },
    { id: 51, question: "크래프팅 시스템에서 실패 확률이 있어야 할까요?", difficulty: "중급" },
    { id: 52, question: "시즌 종료 후 랭킹 보상은 어느 정도 등급까지 주는 게 좋을까요?", difficulty: "중급" },
    { id: 53, question: "포트폴리오 시스템을 실제 구현한다면 얼마나 걸릴 것 같나요?", difficulty: "중급" },
    { id: 54, question: "서버 개발자와 의견 충돌 시 어떻게 조율하나요?", difficulty: "중급" },
    { id: 55, question: "유저가 수식을 역계산해서 최적화하는 것을 어떻게 생각하나요?", difficulty: "고급" },
    { id: 56, question: "랜덤 요소를 완전히 배제한 게임이 재미있을 수 있을까요?", difficulty: "중급" },
    { id: 57, question: "로그라이크의 '메타 진행'은 어느 정도 속도가 적절한가요?", difficulty: "고급" },
    { id: 58, question: "재화가 5종류 이상이면 유저가 혼란스러워할까요?", difficulty: "중급" },
    { id: 59, question: "이벤트 보상이 너무 좋아서 평상시 플레이 동기가 떨어진다면?", difficulty: "고급" },
    { id: 60, question: "성장 곡선에서 구간별 체감 성장도를 어떻게 조절하나요?", difficulty: "고급" },
    { id: 61, question: "신규 유저와 복귀 유저 중 누구에게 더 많은 혜택을 줘야 할까요?", difficulty: "중급" },
    { id: 62, question: "과금 유저와 무과금 유저의 격차를 어떻게 관리하나요?", difficulty: "고급" },
    { id: 63, question: "일일 플레이 시간을 제한하는 시스템(피로도)에 대한 의견은?", difficulty: "중급" },
    { id: 64, question: "자동 사냥 시스템이 게임의 재미를 해칠 수 있을까요?", difficulty: "중급" },
    { id: 65, question: "펫이나 용병 시스템의 밸런스는 어떻게 잡나요?", difficulty: "중급" },
    { id: 66, question: "게임 내 통화(골드) 가치가 폭락하는 것을 막는 방법은?", difficulty: "고급" },
    { id: 67, question: "출석 보상 시스템의 적정 주기는 며칠인가요?", difficulty: "초급" },
    { id: 68, question: "우편함 시스템의 보관 기한은 어떻게 설정하나요?", difficulty: "초급" },
    { id: 69, question: "친구 추천 보상 시스템의 어뷰징을 막는 방법은?", difficulty: "중급" },
    { id: 70, question: "랭킹 시스템에서 동점자 처리는 어떻게 하나요?", difficulty: "중급" },
    { id: 71, question: "게임 내 복권/로또 시스템을 도입하는 것에 대한 의견은?", difficulty: "중급" },
    { id: 72, question: "던전 입장권 시스템의 일일 제한 횟수는 어떻게 정하나요?", difficulty: "중급" },
    { id: 73, question: "스태미나(행동력) 시스템이 필요한 이유는 무엇인가요?", difficulty: "중급" },
    { id: 74, question: "PvP 시즌 기간은 얼마가 적절한가요?", difficulty: "중급" },
    { id: 75, question: "신규 서버와 기존 서버의 통합 시 주의할 점은?", difficulty: "고급" },
    { id: 76, question: "서버 간 이동 시스템을 지원해야 할까요?", difficulty: "중급" },
    { id: 77, question: "게임 내 경매 수수료율은 몇 퍼센트가 적당한가요?", difficulty: "중급" },
    { id: 78, question: "프리미엄 화폐(다이아)의 무료 획득 경로를 열어둬야 할까요?", difficulty: "중급" },
    { id: 79, question: "장비 분해 시 재료 회수율은 어느 정도가 적절한가요?", difficulty: "중급" },
    { id: 80, question: "게임 내 복리 성장 시스템의 위험성은 무엇인가요?", difficulty: "고급" },
    { id: 81, question: "신규 콘텐츠 추가 주기를 어떻게 정하시겠습니까?", difficulty: "중급" },
    { id: 82, question: "유저 레벨 구간별 콘텐츠 소비 속도 차이를 어떻게 관리하나요?", difficulty: "고급" },
    { id: 83, question: "과금 패키지의 가격 정책은 어떻게 수립하나요?", difficulty: "고급" },
    { id: 84, question: "게임 밸런스 패치 후 유저 보상을 제공해야 할까요?", difficulty: "중급" },
    { id: 85, question: "핵심 시스템을 대규모 개편할 때의 리스크 관리 방법은?", difficulty: "고급" },
    { id: 86, question: "A/B 테스트로 시스템을 검증해 본 경험이 있나요?", difficulty: "고급" },
    { id: 87, question: "데이터 로그 분석을 통해 발견한 문제 사례가 있나요?", difficulty: "고급" },
    { id: 88, question: "유저 이탈률이 높은 구간을 발견했을 때 대처 방법은?", difficulty: "고급" },
    { id: 89, question: "게임 수명을 연장하는 가장 효과적인 시스템은 무엇인가요?", difficulty: "고급" },
    { id: 90, question: "엔드 콘텐츠가 부족할 때 임시 방편으로 쓸 수 있는 시스템은?", difficulty: "중급" },
    {
      id: 91,
      question: "유저 간 경쟁을 유도하는 시스템과 협력을 유도하는 시스템 중 어느 것이 더 중요한가요?",
      difficulty: "중급",
    },
    { id: 92, question: "게임 내 뉴스/공지 시스템의 효과적인 운영 방법은?", difficulty: "초급" },
    { id: 93, question: "버그 보고 시스템을 게임 내에 구현해야 할까요?", difficulty: "중급" },
    { id: 94, question: "유저 설문조사를 통한 시스템 개선 경험이 있나요?", difficulty: "중급" },
    { id: 95, question: "라이브 게임의 긴급 패치 기준은 무엇인가요?", difficulty: "고급" },
    { id: 96, question: "롤백이 필요한 상황과 보상 정책은 어떻게 수립하나요?", difficulty: "고급" },
    { id: 97, question: "시스템 기획자로서 가장 중요한 역량은 무엇이라고 생각하나요?", difficulty: "고급" },
    { id: 98, question: "Excel과 Google Sheets 중 어느 것을 선호하나요?", difficulty: "초급" },
    { id: 99, question: "시스템 기획 문서화 시 가장 신경 쓰는 부분은?", difficulty: "중급" },
    { id: 100, question: "본인이 설계한 시스템이 1년 뒤에도 문제없이 작동할 자신이 있나요?", difficulty: "고급" },
  ],

  UI기획: [
    { id: 1, question: "UI와 UX의 차이를 게임 기획 관점에서 설명해 주세요.", difficulty: "초급" },
    { id: 2, question: "가장 좋은 UI는 '없는 UI'라는 말에 대해 어떻게 생각하나요?", difficulty: "중급" },
    { id: 3, question: "정보량이 많은 MMORPG 모바일 화면에서 HUD를 최적화하는 방법은?", difficulty: "고급" },
    { id: 4, question: "유저가 게임 진입 후 5분 내에 이탈하지 않게 만드는 UX 설계의 핵심은?", difficulty: "고급" },
    { id: 5, question: "뎁스(Depth)가 깊은 메뉴 구조를 개선하기 위한 본인만의 방법론이 있나요?", difficulty: "중급" },
    { id: 6, question: "심미성(디자인)과 편의성(기능)이 충돌할 때 어떤 기준으로 결정하나요?", difficulty: "고급" },
    { id: 7, question: "색각 이상자를 위한 UI 접근성(Accessibility) 모드를 기획해 본 적 있나요?", difficulty: "중급" },
    { id: 8, question: "피드백(터치, 사운드, 이펙트)이 UX에 미치는 영향에 대해 설명해 주세요.", difficulty: "중급" },
    { id: 9, question: "튜토리얼을 스킵하는 유저들에게 필수 정보를 전달하는 UI적 기법은?", difficulty: "중급" },
    { id: 10, question: "로딩 화면(Loading Screen)을 지루하지 않게 활용하는 아이디어가 있나요?", difficulty: "초급" },
    { id: 11, question: "인벤토리 정렬 및 필터링 기능 기획 시 필수적으로 들어가야 할 항목은?", difficulty: "초급" },
    { id: 12, question: "폰트 크기나 가독성이 게임 플레이 피로도에 미치는 영향은?", difficulty: "중급" },
    { id: 13, question: "최근 플레이한 게임 중 UI가 가장 불편했던 게임과 개선안을 말해보세요.", difficulty: "중급" },
    {
      id: 14,
      question: "반응형 UI(디바이스 해상도 대응) 기획 시 가장 골치 아픈 요소는 무엇인가요?",
      difficulty: "중급",
    },
    {
      id: 15,
      question: "버튼의 위치나 크기가 유저의 조작 실수에 미치는 영향을 분석해 본 적 있나요?",
      difficulty: "중급",
    },
    { id: 16, question: "'레드 닷(알림 표시)'이 너무 많으면 발생하는 문제와 해결책은?", difficulty: "중급" },
    { id: 17, question: "아이콘만으로 기능을 직관적으로 설명하기 위해 어떤 메타포를 사용하나요?", difficulty: "중급" },
    { id: 18, question: "게임의 세계관(톤앤매너)을 UI 디자인에 녹여낸 사례를 설명해 주세요.", difficulty: "고급" },
    { id: 19, question: "터치 디바이스와 키보드/마우스 조작 UI의 기획적 차이점은?", difficulty: "중급" },
    { id: 20, question: "팝업창 남발을 줄이고 정보를 전달할 수 있는 대체 UI 방식은?", difficulty: "중급" },
    { id: 21, question: "포트폴리오에 있는 와이어프레임은 어떤 툴(Figma, XD 등)을 사용했나요?", difficulty: "초급" },
    {
      id: 22,
      question: "유저 테스트(FGT) 결과 UI가 불편하다는 피드백이 많다면 어떻게 수정하시겠습니까?",
      difficulty: "고급",
    },
    {
      id: 23,
      question: "글로벌 서비스를 위한 UI 텍스트 공간(번역 길이 대응)은 어떻게 확보하나요?",
      difficulty: "중급",
    },
    { id: 24, question: "체력바(HP Bar) 디자인에서 시인성을 높이기 위한 기획적 장치는?", difficulty: "초급" },
    { id: 25, question: "컷신에서 UI를 숨기거나 변형할 때의 전환 연출은 어떻게 기획하나요?", difficulty: "중급" },
    { id: 26, question: "미니맵 UI에 표시해야 할 필수 정보와 제외해야 할 정보의 기준은?", difficulty: "중급" },
    { id: 27, question: "상점 UI에서 구매 전환율을 높이기 위한 배치 전략이 있나요?", difficulty: "고급" },
    { id: 28, question: "퀘스트 수락부터 완료까지의 UX 동선을 최적화한 경험이 있나요?", difficulty: "중급" },
    { id: 29, question: "UI 리소스 최적화(아틀라스 등)에 대해 고려하며 기획하나요?", difficulty: "고급" },
    { id: 30, question: "모션 그래픽이나 UI 애니메이션이 게임의 '손맛'에 기여하는 부분은?", difficulty: "중급" },
    // 뉘앙스 변형 및 상황 추가 (31-100)
    { id: 31, question: "UI 기획자와 UX 기획자의 역할 차이는 무엇인가요?", difficulty: "초급" },
    { id: 32, question: "UI가 없어도 게임이 가능한 경우는 언제인가요?", difficulty: "중급" },
    { id: 33, question: "PC MMORPG의 HUD를 모바일로 옮길 때 가장 큰 난제는?", difficulty: "중급" },
    { id: 34, question: "첫 5분 이탈을 막기 위한 온보딩 UX의 핵심 요소 3가지는?", difficulty: "고급" },
    { id: 35, question: "3뎁스 이상의 메뉴는 무조건 나쁜 UX인가요?", difficulty: "중급" },
    { id: 36, question: "예쁘지만 불편한 UI와 못생겼지만 편한 UI 중 선택한다면?", difficulty: "중급" },
    { id: 37, question: "색맹 모드 외에 청각 장애인을 위한 UI 고려 사항은?", difficulty: "중급" },
    { id: 38, question: "햅틱 피드백이 게임 몰입도에 미치는 영향은?", difficulty: "중급" },
    { id: 39, question: "강제 튜토리얼과 선택적 튜토리얼 중 어느 것이 나을까요?", difficulty: "중급" },
    { id: 40, question: "로딩 화면에 미니게임을 넣는 것에 대한 의견은?", difficulty: "초급" },
    { id: 41, question: "인벤토리 자동 정렬 기능의 기본값은 무엇으로 설정해야 할까요?", difficulty: "초급" },
    { id: 42, question: "폰트 크기를 유저가 직접 조절할 수 있게 해야 할까요?", difficulty: "중급" },
    { id: 43, question: "최근 플레이한 게임 중 UI가 가장 훌륭했던 사례는?", difficulty: "초급" },
    { id: 44, question: "태블릿과 스마트폰의 UI 레이아웃을 다르게 가져가야 할까요?", difficulty: "중급" },
    { id: 45, question: "오른손잡이와 왼손잡이를 위한 UI 배치 옵션이 필요한가요?", difficulty: "중급" },
    { id: 46, question: "알림 배지가 100개 이상일 때 표시 방법은?", difficulty: "초급" },
    { id: 47, question: "텍스트 없이 아이콘만으로 UI를 구성할 수 있을까요?", difficulty: "중급" },
    { id: 48, question: "판타지 게임과 SF 게임의 UI 디자인 접근 방식 차이는?", difficulty: "중급" },
    { id: 49, question: "모바일 게임에서 PC 게임 수준의 복잡한 조작을 구현하려면?", difficulty: "고급" },
    { id: 50, question: "중요한 정보를 팝업 없이 전달하는 방법 3가지를 말씀해주세요.", difficulty: "중급" },
    { id: 51, question: "와이어프레임과 프로토타입의 차이는 무엇인가요?", difficulty: "초급" },
    { id: 52, question: "UI 테스트에서 가장 빈번하게 발견되는 문제는 무엇인가요?", difficulty: "중급" },
    { id: 53, question: "다국어 지원 시 텍스트 길이가 2배 이상 차이나는 경우 대처법은?", difficulty: "중급" },
    { id: 54, question: "HP 바 색상으로 빨강 대신 다른 색을 써야 하는 경우는?", difficulty: "중급" },
    { id: 55, question: "컷신 중 UI를 완전히 숨기는 것과 최소화하는 것 중 어느 것이 나을까요?", difficulty: "중급" },
    { id: 56, question: "미니맵에 적 위치를 표시하는 것이 게임 밸런스에 미치는 영향은?", difficulty: "중급" },
    { id: 57, question: "상점에서 '한정 특가' UI 배치가 과금 유도에 미치는 영향은?", difficulty: "고급" },
    { id: 58, question: "퀘스트 자동 추적 기능이 게임 몰입을 방해할 수 있나요?", difficulty: "중급" },
    { id: 59, question: "UI 스프라이트 아틀라스 최적화를 직접 해본 경험이 있나요?", difficulty: "고급" },
    { id: 60, question: "버튼 클릭 시 애니메이션 지연이 0.1초 이상이면 불편할까요?", difficulty: "중급" },
    { id: 61, question: "다크 모드와 라이트 모드 중 어느 것을 기본으로 해야 할까요?", difficulty: "초급" },
    { id: 62, question: "스킵 가능한 연출과 스킵 불가능한 연출의 기준은?", difficulty: "중급" },
    { id: 63, question: "게임 설정 메뉴에서 가장 많이 사용되는 옵션 3가지는?", difficulty: "초급" },
    { id: 64, question: "UI 사운드가 없는 게임은 어색하게 느껴질까요?", difficulty: "초급" },
    { id: 65, question: "채팅창 UI 디자인에서 가장 중요한 요소는 무엇인가요?", difficulty: "초급" },
    { id: 66, question: "친구 목록 UI에서 온라인/오프라인 구분을 어떻게 표현하나요?", difficulty: "초급" },
    { id: 67, question: "길드 UI에서 필수적으로 들어가야 할 기능은 무엇인가요?", difficulty: "초급" },
    { id: 68, question: "우편함 UI에서 일괄 수령 기능을 어떻게 배치하시겠습니까?", difficulty: "초급" },
    { id: 69, question: "전투 중 스킬 버튼 배치는 몇 개까지가 적절한가요?", difficulty: "중급" },
    {
      id: 70,
      question: "가챠 연출 UI에서 등급을 미리 알려주는 것과 나중에 알려주는 것 중 어느 것이 나을까요?",
      difficulty: "중급",
    },
    { id: 71, question: "강화 성공/실패 연출 UI는 얼마나 길어야 적절한가요?", difficulty: "중급" },
    { id: 72, question: "맵 이동 로딩 중 팁을 표시하는 것이 효과적인가요?", difficulty: "초급" },
    { id: 73, question: "배틀 패스 UI에서 유료/무료 보상을 어떻게 구분해서 보여주나요?", difficulty: "중급" },
    { id: 74, question: "이벤트 배너가 너무 많을 때 UI 처리 방법은?", difficulty: "중급" },
    { id: 75, question: "신규 업데이트 내용을 UI로 효과적으로 안내하는 방법은?", difficulty: "중급" },
    { id: 76, question: "VIP 시스템 UI에서 등급별 혜택을 어떻게 시각화하나요?", difficulty: "중급" },
    { id: 77, question: "랭킹 UI에서 본인 순위를 항상 표시해야 할까요?", difficulty: "중급" },
    { id: 78, question: "업적 달성 알림은 즉시 팝업으로 띄워야 할까요?", difficulty: "중급" },
    { id: 79, question: "파티 초대 알림이 전투 중에 떠도 괜찮을까요?", difficulty: "중급" },
    { id: 80, question: "스탯 분배 UI에서 실수로 잘못 찍는 것을 방지하는 UX는?", difficulty: "중급" },
    { id: 81, question: "장비 비교 UI를 어떻게 디자인하는 것이 가장 직관적일까요?", difficulty: "중급" },
    { id: 82, question: "스킬 트리 UI에서 선행 조건을 어떻게 시각화하나요?", difficulty: "중급" },
    { id: 83, question: "던전 난이도 선택 UI를 어떻게 배치하시겠습니까?", difficulty: "초급" },
    { id: 84, question: "보스 레이드 입장 전 준비 상태 체크 UI는 어떻게 만드나요?", difficulty: "중급" },
    { id: 85, question: "PvP 매칭 대기 중 예상 시간을 표시해야 할까요?", difficulty: "중급" },
    { id: 86, question: "전투 승리 보상 UI에서 애니메이션은 필수인가요?", difficulty: "중급" },
    { id: 87, question: "레벨업 연출 UI는 게임 진행을 멈춰야 할까요?", difficulty: "중급" },
    { id: 88, question: "모바일 게임에서 PC처럼 마우스 오버 툴팁을 대체하는 방법은?", difficulty: "중급" },
    { id: 89, question: "컨트롤러 진동 세기를 UI 설정에 넣어야 할까요?", difficulty: "초급" },
    { id: 90, question: "UI 프레임 드롭이 게임 플레이에 미치는 영향은?", difficulty: "고급" },
    { id: 91, question: "Figma와 Adobe XD 중 어느 툴을 선호하나요?", difficulty: "초급" },
    { id: 92, question: "UI 목업 단계에서 실제 데이터를 넣어야 할까요?", difficulty: "초급" },
    { id: 93, question: "UI 기획서에 반드시 포함되어야 할 항목은 무엇인가요?", difficulty: "중급" },
    { id: 94, question: "디자이너가 기획 의도를 잘못 이해했을 때 대응 방법은?", difficulty: "중급" },
    { id: 95, question: "UI 애니메이션 속도는 몇 프레임이 가장 자연스러울까요?", difficulty: "중급" },
    { id: 96, question: "UI 버튼의 히트 박스는 실제 이미지보다 얼마나 커야 할까요?", difficulty: "고급" },
    { id: 97, question: "UI 기획자에게 가장 필요한 능력은 무엇이라고 생각하나요?", difficulty: "고급" },
    { id: 98, question: "UI 트렌드를 어디서 공부하나요?", difficulty: "초급" },
    { id: 99, question: "본인이 가장 자신 있는 UI 영역은 무엇인가요?", difficulty: "중급" },
    { id: 100, question: "5년 후 게임 UI는 어떻게 변할 것이라고 예상하나요?", difficulty: "고급" },
  ],

  전투스킬기획: [
    { id: 1, question: "본인이 생각하는 '타격감'의 3대 요소는 무엇인가요?", difficulty: "중급" },
    { id: 2, question: "턴제 전투와 실시간 액션 전투의 기획적 접근 차이는 무엇인가요?", difficulty: "중급" },
    { id: 3, question: "쿨타임과 자원(MP/SP) 소모의 상관관계를 어떻게 밸런싱 하나요?", difficulty: "고급" },
    {
      id: 4,
      question: "OP(Over Power) 캐릭터가 발생했을 때 너프와 버프 중 어떤 방향을 선호하나요?",
      difficulty: "고급",
    },
    { id: 5, question: "PvP 밸런스와 PvE 밸런스를 분리해서 적용해야 한다고 생각하나요?", difficulty: "고급" },
    { id: 6, question: "스킬의 선딜레이(선딜)와 후딜레이(후딜)가 전투의 긴장감에 미치는 영향은?", difficulty: "중급" },
    { id: 7, question: "상태 이상(CC기)이 너무 강력해서 전투가 루즈해지는 것을 막는 방법은?", difficulty: "고급" },
    { id: 8, question: "'회피'나 '막기' 같은 방어 기제가 너무 좋으면 발생하는 문제는?", difficulty: "중급" },
    { id: 9, question: "다수의 적을 쓸어버리는 '핵 앤 슬래시'의 재미 핵심은 무엇인가요?", difficulty: "중급" },
    { id: 10, question: "오토 타겟팅 시스템에서 유저가 원하는 대상을 정확히 때리게 하는 로직은?", difficulty: "고급" },
    { id: 11, question: "힐러나 서포터 직군이 전투에서 재미를 느끼게 하려면 어떻게 해야 할까요?", difficulty: "중급" },
    {
      id: 12,
      question: "속성(불, 물, 풀 등) 상성 시스템이 전투의 복잡도만 높이는 경우를 본 적 있나요?",
      difficulty: "중급",
    },
    { id: 13, question: "근거리 캐릭터와 원거리 캐릭터의 PvP 유불리를 어떻게 맞추시겠습니까?", difficulty: "고급" },
    { id: 14, question: "스킬 트리가 복잡할수록 좋은 게임일까요? 직관적인 게 좋을까요?", difficulty: "중급" },
    { id: 15, question: "궁극기(필살기)의 사용 빈도와 위력은 어떤 비율이 적절할까요?", difficulty: "중급" },
    { id: 16, question: "몬스터의 피격 리액션(경직, 넉백)이 전투 템포에 미치는 영향은?", difficulty: "중급" },
    { id: 17, question: "전투 중 시점(Camera) 처리가 엉망이라 불쾌했던 경험과 해결책은?", difficulty: "중급" },
    { id: 18, question: "콤보 시스템을 기획할 때 초보자와 숙련자의 격차를 어떻게 조절하나요?", difficulty: "고급" },
    { id: 19, question: "'패링(쳐내기)' 시스템의 리스크와 리턴을 어떻게 설계하시나요?", difficulty: "고급" },
    { id: 20, question: "버려지는 스킬이 없도록 만들기 위한 본인만의 밸런싱 철학이 있나요?", difficulty: "고급" },
    { id: 21, question: "포트폴리오의 전투 기획에서 가장 창의적이었던 메커니즘은?", difficulty: "고급" },
    { id: 22, question: "랜덤 크리티컬(치명타)이 e스포츠나 경쟁 게임에 미치는 영향은?", difficulty: "중급" },
    { id: 23, question: "보스전에서 단순한 '딜 찍누(딜로 찍어 누르기)'를 방지하기 위한 기믹은?", difficulty: "고급" },
    { id: 24, question: "전투 공식(대미지 산출 공식)을 직접 설계해 본 적 있나요?", difficulty: "고급" },
    { id: 25, question: "슈퍼 아머(피격 무시) 상태의 적을 공략하게 만드는 방법은?", difficulty: "중급" },
    { id: 26, question: "투사체(Projectile) 속도와 히트 박스 크기가 명중률에 미치는 영향은?", difficulty: "고급" },
    { id: 27, question: "전투 사운드가 타격감의 몇 퍼센트를 차지한다고 생각하나요?", difficulty: "중급" },
    { id: 28, question: "조작 난이도가 높은 캐릭터는 반드시 성능이 좋아야 할까요?", difficulty: "중급" },
    { id: 29, question: "AI 동료(NPC)와 함께 싸울 때 AI가 너무 멍청해 보이지 않게 하려면?", difficulty: "중급" },
    { id: 30, question: "모바일의 가상 패드 조작감을 개선하기 위한 아이디어가 있나요?", difficulty: "중급" },
    // 뉘앙스 변형 및 상황 추가 (31-100)
    { id: 31, question: "타격감에서 시각 효과와 사운드 중 어느 것이 더 중요한가요?", difficulty: "중급" },
    { id: 32, question: "턴제 전투에서 속도(AGI) 스탯이 필요한 이유는?", difficulty: "중급" },
    { id: 33, question: "쿨타임 없이 자원만으로 스킬을 제한하는 시스템의 장단점은?", difficulty: "고급" },
    { id: 34, question: "OP 캐릭터를 너프했을 때 유저 보상을 제공해야 할까요?", difficulty: "고급" },
    { id: 35, question: "PvP와 PvE 밸런스 분리 시 유저 혼란을 줄이는 방법은?", difficulty: "고급" },
    { id: 36, question: "선딜이 긴 스킬은 어떤 보상이 따라야 할까요?", difficulty: "중급" },
    { id: 37, question: "CC기 지속시간과 쿨타임의 적정 비율은?", difficulty: "고급" },
    { id: 38, question: "회피가 무적이 되는 시스템과 회피율 퍼센트 시스템 중 어느 것이 나을까요?", difficulty: "중급" },
    { id: 39, question: "핵 앤 슬래시에서 적의 수가 너무 많으면 오히려 재미없어지는 이유는?", difficulty: "중급" },
    { id: 40, question: "타겟팅 우선순위를 유저가 설정할 수 있어야 할까요?", difficulty: "중급" },
    { id: 41, question: "힐러가 DPS 역할도 할 수 있게 만드는 것에 대한 의견은?", difficulty: "중급" },
    { id: 42, question: "속성 상성 시스템 없이도 전략성을 확보하는 방법은?", difficulty: "고급" },
    { id: 43, question: "근거리 캐릭터에게 돌진기를 주는 것만으로 충분할까요?", difficulty: "중급" },
    { id: 44, question: "스킬 특성화 시스템이 너무 복잡하면 생기는 문제는?", difficulty: "중급" },
    { id: 45, question: "궁극기 게이지를 빠르게 채우는 방법을 다양화해야 할까요?", difficulty: "중급" },
    { id: 46, question: "피격 리액션이 전혀 없는 적은 어떤 느낌을 주나요?", difficulty: "초급" },
    { id: 47, question: "카메라가 적을 놓쳐서 백어택을 당하는 상황을 방지하려면?", difficulty: "중급" },
    { id: 48, question: "콤보 입력 타이밍 판정을 너무 짧게 하면 생기는 문제는?", difficulty: "중급" },
    { id: 49, question: "패링 성공 보상이 너무 좋으면 일반 공격을 안 쓰게 되나요?", difficulty: "중급" },
    { id: 50, question: "모든 스킬이 쓸모있게 만들기 위한 방법 3가지는?", difficulty: "고급" },
    { id: 51, question: "포트폴리오 전투 시스템의 가장 큰 약점은 무엇인가요?", difficulty: "고급" },
    { id: 52, question: "크리티컬 확률을 100%로 만들 수 있게 해도 될까요?", difficulty: "중급" },
    { id: 53, question: "보스의 패턴 변화 타이밍을 HP 구간으로 정하는 것의 문제점은?", difficulty: "고급" },
    {
      id: 54,
      question: "대미지 공식에서 방어력의 체감 효과를 선형으로 할 것인가 비선형으로 할 것인가?",
      difficulty: "고급",
    },
    { id: 55, question: "슈퍼 아머를 깨는 전용 스킬이 필요한가요?", difficulty: "중급" },
    { id: 56, question: "투사체가 벽을 관통해야 할까요 막혀야 할까요?", difficulty: "중급" },
    { id: 57, question: "타격 사운드 없이 음악만 있는 전투는 어떤 느낌일까요?", difficulty: "초급" },
    { id: 58, question: "어려운 캐릭터의 성능을 더 높게 설정하는 것이 공정한가요?", difficulty: "중급" },
    {
      id: 59,
      question: "NPC 동료가 너무 강하면 유저가 할 일이 없어지는 문제를 어떻게 해결하나요?",
      difficulty: "중급",
    },
    { id: 60, question: "모바일 가상 패드 크기를 유저가 조절할 수 있게 해야 할까요?", difficulty: "중급" },
    { id: 61, question: "공중 콤보 시스템을 기획해 본 경험이 있나요?", difficulty: "중급" },
    { id: 62, question: "스킬 캔슬 시스템이 전투 속도에 미치는 영향은?", difficulty: "중급" },
    { id: 63, question: "반격 타이밍 판정을 어느 정도로 관대하게 해야 할까요?", difficulty: "중급" },
    { id: 64, question: "스태미나 시스템이 있는 전투와 없는 전투의 차이는?", difficulty: "중급" },
    { id: 65, question: "무기 내구도 시스템이 전투에 미치는 영향은?", difficulty: "중급" },
    { id: 66, question: "버프 아이콘이 너무 많을 때 UI적 해결 방법은?", difficulty: "중급" },
    { id: 67, question: "광역기와 단일 타겟 스킬의 대미지 배율 차이를 어떻게 정하나요?", difficulty: "고급" },
    { id: 68, question: "도트 대미지(지속 피해)의 적정 틱(Tick) 간격은?", difficulty: "중급" },
    { id: 69, question: "즉사기 스킬을 PvP에서 허용해도 될까요?", difficulty: "고급" },
    { id: 70, question: "부활 스킬이 전투 밸런스를 무너뜨릴 수 있나요?", difficulty: "중급" },
    { id: 71, question: "전투 중 아이템 사용에 쿨타임을 줘야 할까요?", difficulty: "중급" },
    { id: 72, question: "체인 스킬(연계기) 시스템의 보상은 어느 정도여야 할까요?", difficulty: "중급" },
    { id: 73, question: "스킬 강화 시 쿨타임 감소와 대미지 증가 중 무엇이 나을까요?", difficulty: "중급" },
    { id: 74, question: "패시브 스킬이 너무 많으면 전투가 지루해지나요?", difficulty: "중급" },
    { id: 75, question: "카운터 공격 시스템을 모든 직업에 줘야 할까요?", difficulty: "중급" },
    { id: 76, question: "스킬 이펙트가 화려할수록 타격감이 좋아지나요?", difficulty: "중급" },
    { id: 77, question: "경직 저항 스탯이 너무 높으면 생기는 문제는?", difficulty: "중급" },
    { id: 78, question: "약점 부위 공격 시스템이 전투의 깊이를 더할까요?", difficulty: "중급" },
    { id: 79, question: "백어택(뒤잡기) 보너스는 몇 퍼센트가 적당한가요?", difficulty: "중급" },
    { id: 80, question: "전투 중 시간 정지 스킬을 어떻게 구현하시겠습니까?", difficulty: "고급" },
    { id: 81, question: "오버킬(과잉 대미지) 표현이 필요한 이유는 무엇인가요?", difficulty: "중급" },
    { id: 82, question: "다단히트 스킬과 한방 스킬 중 어느 것이 더 재밌나요?", difficulty: "중급" },
    { id: 83, question: "스킬 사거리를 시각적으로 표시해야 할까요?", difficulty: "중급" },
    { id: 84, question: "스킬 프리뷰(미리보기) 기능이 전투에 도움이 될까요?", difficulty: "중급" },
    { id: 85, question: "전투 중 캐릭터 교체 시스템을 어떻게 설계하시겠습니까?", difficulty: "고급" },
    { id: 86, question: "합체기(협동 스킬) 시스템의 발동 조건은 어떻게 설정하나요?", difficulty: "중급" },
    { id: 87, question: "각성 시스템(버스트 모드)의 지속시간은 얼마가 적절한가요?", difficulty: "중급" },
    { id: 88, question: "스킬 쿨타임 초기화 아이템의 밸런스는?", difficulty: "중급" },
    { id: 89, question: "원거리 캐릭터의 탄환 개수를 제한해야 할까요?", difficulty: "중급" },
    { id: 90, question: "보스 그로기(기절) 상태의 적정 지속시간은?", difficulty: "중급" },
    { id: 91, question: "스킬 선택지가 너무 많으면 오히려 불편할까요?", difficulty: "중급" },
    { id: 92, question: "전투 난이도 조절을 적 능력치로 할 것인가 AI로 할 것인가?", difficulty: "고급" },
    { id: 93, question: "스킬 데이터를 엑셀로 관리하나요 JSON으로 관리하나요?", difficulty: "고급" },
    { id: 94, question: "전투 밸런스 테스트는 주로 어떤 방식으로 진행하나요?", difficulty: "고급" },
    { id: 95, question: "전투 기획자에게 가장 필요한 게임 플레이 경험은?", difficulty: "중급" },
    { id: 96, question: "액션 게임의 프레임 드롭이 전투에 미치는 영향은?", difficulty: "고급" },
    { id: 97, question: "본인이 가장 좋아하는 전투 시스템은 어떤 게임에 있나요?", difficulty: "초급" },
    { id: 98, question: "전투 기획에서 가장 어려운 부분은 무엇인가요?", difficulty: "중급" },
    { id: 99, question: "전투 밸런스와 재미 중 무엇이 더 우선인가요?", difficulty: "고급" },
    { id: 100, question: "5년 후 전투 시스템은 어떻게 진화할 것 같나요?", difficulty: "고급" },
  ],

  "캐릭터 및 몬스터기획": [
    { id: 1, question: "매력적인 캐릭터를 만들기 위해 외형 외에 가장 중요한 요소는?", difficulty: "중급" },
    { id: 2, question: "캐릭터의 성격(Tsundere 등)을 스킬이나 전투 스타일에 어떻게 반영하나요?", difficulty: "중급" },
    {
      id: 3,
      question: "몬스터 AI를 기획할 때 FSM(유한 상태 머신)과 비헤이비어 트리 중 무엇을 선호하나요?",
      difficulty: "고급",
    },
    { id: 4, question: "유저가 몬스터의 패턴을 '합리적'이라고 느끼게 만드는 기준은?", difficulty: "고급" },
    { id: 5, question: "보스 몬스터의 페이즈(Phase) 변화 시 난이도 곡선은 어떻게 그리나요?", difficulty: "고급" },
    { id: 6, question: "잡몹, 정예몹, 보스몹의 역할과 행동 패턴의 결정적 차이는?", difficulty: "중급" },
    {
      id: 7,
      question: "몬스터가 유저를 인식하는 범위(Aggro Range)와 추격 중단 거리는 어떻게 설정하나요?",
      difficulty: "중급",
    },
    { id: 8, question: "수집형 RPG에서 낮은 등급(R, B급) 캐릭터의 활용 방안은?", difficulty: "중급" },
    { id: 9, question: "캐릭터 간의 관계(인연)가 실제 인게임 능력치에 영향을 줘야 할까요?", difficulty: "중급" },
    { id: 10, question: "인간형 몬스터와 괴수형 몬스터의 기획적 접근 차이는?", difficulty: "중급" },
    { id: 11, question: "'팔레트 스왑(색깔 놀이)' 몬스터를 유저들이 싫어하지 않게 활용하는 법은?", difficulty: "중급" },
    {
      id: 12,
      question: "몬스터가 너무 똑똑해서 유저가 스트레스를 받지 않도록 '멍청하게' 만드는 요소는?",
      difficulty: "중급",
    },
    {
      id: 13,
      question: "특정 몬스터를 잡기 위해 특정 캐릭터가 강제되는 상황에 대해 어떻게 생각하나요?",
      difficulty: "고급",
    },
    { id: 14, question: "거대 보스 몬스터와의 전투에서 발바닥만 때리는 현상을 방지하려면?", difficulty: "중급" },
    { id: 15, question: "포트폴리오에 있는 몬스터의 '정찰' 패턴은 어떤 의도로 기획했나요?", difficulty: "고급" },
    { id: 16, question: "캐릭터의 배경 스토리(Lore)가 게임 시스템과 충돌할 때 어떻게 해결하나요?", difficulty: "고급" },
    { id: 17, question: "몬스터의 등장(Spawn) 연출이 게임의 몰입도에 미치는 영향은?", difficulty: "중급" },
    { id: 18, question: "비선공 몬스터와 선공 몬스터의 배치 비율은 어떻게 정하나요?", difficulty: "중급" },
    { id: 19, question: "몬스터가 군집을 이루어 협공하는 AI를 기획해 본 적 있나요?", difficulty: "고급" },
    { id: 20, question: "보스의 광폭화(Enrage) 패턴은 꼭 필요한가요? 이유는 무엇인가요?", difficulty: "중급" },
    { id: 21, question: "캐릭터 밸런스를 맞출 때 '가위바위보' 상성 구조를 선호하나요?", difficulty: "중급" },
    { id: 22, question: "NPC의 대사나 행동을 통해 세계관을 전달하는 방법은?", difficulty: "중급" },
    { id: 23, question: "몬스터의 약점 부위 파괴 시스템을 기획할 때 고려할 점은?", difficulty: "중급" },
    { id: 24, question: "하늘을 나는 몬스터를 근거리 캐릭터가 공략하게 만드는 방법은?", difficulty: "중급" },
    { id: 25, question: "몬스터 스킬 사용 전조(Telegraph)를 시각적으로 어떻게 표현하나요?", difficulty: "중급" },
    { id: 26, question: "캐릭터의 이동 속도와 점프력이 맵 디자인에 미치는 제약은?", difficulty: "고급" },
    { id: 27, question: "본인이 만든 캐릭터 중 가장 애착이 가는 캐릭터와 그 이유는?", difficulty: "중급" },
    { id: 28, question: "몬스터 도감 시스템이 유저에게 주는 동기부여는 무엇일까요?", difficulty: "중급" },
    { id: 29, question: "AI가 플레이어를 놓쳤을 때 제자리로 돌아가는 과정(리셋) 처리 방법은?", difficulty: "중급" },
    { id: 30, question: "캐릭터 코스튬(스킨)이 피격 판정(Hit Box)에 영향을 주면 안 되는 이유는?", difficulty: "고급" },
    // 뉘앙스 변형 및 상황 추가 (31-100)
    { id: 31, question: "캐릭터의 매력을 결정하는 요소 5가지를 나열해주세요.", difficulty: "중급" },
    { id: 32, question: "성격이 전투 스타일에 반영된 게임 캐릭터 사례를 아나요?", difficulty: "초급" },
    { id: 33, question: "FSM과 비헤이비어 트리의 가장 큰 차이점은?", difficulty: "고급" },
    { id: 34, question: "몬스터 패턴이 랜덤일 때와 정해진 순서일 때의 장단점은?", difficulty: "중급" },
    { id: 35, question: "보스 페이즈 전환 시 무적 시간을 줘야 할까요?", difficulty: "중급" },
    { id: 36, question: "잡몹의 적정 체력은 플레이어 DPS의 몇 초분이어야 할까요?", difficulty: "중급" },
    { id: 37, question: "어그로 범위가 너무 넓으면 생기는 문제는?", difficulty: "중급" },
    { id: 38, question: "낮은 등급 캐릭터를 재료로만 쓰게 하는 것이 좋을까요?", difficulty: "중급" },
    { id: 39, question: "캐릭터 인연 시스템이 과금 유도로 느껴질 수 있나요?", difficulty: "중급" },
    { id: 40, question: "인간형 몬스터에게 회화(대화) 능력을 줘야 할까요?", difficulty: "중급" },
    { id: 41, question: "색깔만 다른 몬스터의 능력치는 얼마나 차이나야 할까요?", difficulty: "중급" },
    { id: 42, question: "몬스터 AI가 일부러 실수하는 연출을 넣어본 적 있나요?", difficulty: "고급" },
    { id: 43, question: "카운터 캐릭터(하드 카운터) 구조에 대해 어떻게 생각하나요?", difficulty: "고급" },
    { id: 44, question: "거대 보스의 약점이 머리일 때 조준이 어려운 문제를 어떻게 해결하나요?", difficulty: "중급" },
    { id: 45, question: "몬스터가 정찰 상태에서 전투 상태로 전환되는 조건은?", difficulty: "중급" },
    { id: 46, question: "스토리와 게임플레이가 충돌할 때 무엇을 우선하나요?", difficulty: "고급" },
    { id: 47, question: "몬스터 등장 연출에 컷신이 필요한 경우는 언제인가요?", difficulty: "중급" },
    { id: 48, question: "선공 몬스터가 너무 많으면 유저가 피로해질까요?", difficulty: "중급" },
    { id: 49, question: "몬스터 협공 AI에서 포위 전술을 어떻게 구현하나요?", difficulty: "고급" },
    { id: 50, question: "광폭화 시 공격력만 올릴 것인가 패턴도 바꿀 것인가?", difficulty: "중급" },
    { id: 51, question: "상성 구조 없이 캐릭터 다양성을 확보할 수 있나요?", difficulty: "고급" },
    { id: 52, question: "NPC의 반복되는 대사가 짜증날 때 해결 방법은?", difficulty: "초급" },
    { id: 53, question: "약점 부위 파괴 시 보상은 무엇으로 줘야 할까요?", difficulty: "중급" },
    { id: 54, question: "비행 몬스터에게 착지 패턴을 강제해야 할까요?", difficulty: "중급" },
    { id: 55, question: "몬스터 공격 예고가 너무 길면 긴장감이 떨어지나요?", difficulty: "중급" },
    { id: 56, question: "캐릭터의 이동 속도가 맵 크기 설계에 미치는 영향은?", difficulty: "고급" },
    { id: 57, question: "본인이 만든 캐릭터가 인기가 없었던 이유는 무엇일까요?", difficulty: "중급" },
    { id: 58, question: "몬스터 도감 완성도가 보상과 연결되어야 할까요?", difficulty: "중급" },
    { id: 59, question: "AI 리셋 시 체력도 회복되어야 할까요?", difficulty: "중급" },
    { id: 60, question: "스킨이 시인성에 영향을 줘서 PvP에서 불리할 수 있나요?", difficulty: "고급" },
    { id: 61, question: "캐릭터 성우 연기가 캐릭터 인기에 미치는 영향은?", difficulty: "중급" },
    { id: 62, question: "캐릭터 육성 재료가 캐릭터마다 다르면 불편할까요?", difficulty: "중급" },
    { id: 63, question: "몬스터 레벨과 플레이어 레벨의 격차가 얼마나 나야 어려움을 느낄까요?", difficulty: "중급" },
    { id: 64, question: "보스 몬스터의 체력 바를 여러 칸으로 나누는 이유는?", difficulty: "중급" },
    { id: 65, question: "캐릭터 전용 무기를 만드는 것이 밸런스에 유리한가요?", difficulty: "중급" },
    { id: 66, question: "몬스터의 공격력이 방어력을 무시하는 패턴이 필요한가요?", difficulty: "중급" },
    { id: 67, question: "캐릭터 스토리를 게임 내에서 어떻게 전달하시겠습니까?", difficulty: "중급" },
    { id: 68, question: "몬스터의 도망 패턴을 넣는 것에 대한 의견은?", difficulty: "중급" },
    { id: 69, question: "캐릭터별 전용 스테이지가 필요한가요?", difficulty: "중급" },
    { id: 70, question: "동일 몬스터를 여러 지역에 배치할 때 변화를 줘야 할까요?", difficulty: "중급" },
    { id: 71, question: "캐릭터 인기 투표 결과를 밸런스에 반영해야 할까요?", difficulty: "중급" },
    { id: 72, question: "몬스터 리스폰 타임을 유저가 알 수 있게 해야 할까요?", difficulty: "중급" },
    { id: 73, question: "캐릭터 각성 전후 성능 차이는 얼마나 나야 할까요?", difficulty: "중급" },
    { id: 74, question: "몬스터가 회복 아이템을 사용하는 패턴에 대한 의견은?", difficulty: "중급" },
    { id: 75, question: "캐릭터 중복 획득 시 처리 방법은?", difficulty: "중급" },
    { id: 76, question: "몬스터가 플레이어의 버프를 해제하는 스킬을 써도 될까요?", difficulty: "중급" },
    { id: 77, question: "캐릭터 성별 비율을 어떻게 가져가는 것이 좋을까요?", difficulty: "초급" },
    { id: 78, question: "몬스터의 시야각을 설정하는 이유는 무엇인가요?", difficulty: "중급" },
    { id: 79, question: "캐릭터 콜라보레이션 기획 경험이 있나요?", difficulty: "중급" },
    { id: 80, question: "몬스터가 소환하는 하수인의 적정 수는?", difficulty: "중급" },
    { id: 81, question: "캐릭터 표정 변화가 게임 플레이에 영향을 줄 수 있나요?", difficulty: "초급" },
    { id: 82, question: "보스 몬스터의 고유 BGM이 필요한가요?", difficulty: "초급" },
    { id: 83, question: "캐릭터 신뢰도/호감도 시스템 설계 방법은?", difficulty: "중급" },
    { id: 84, question: "몬스터가 함정을 설치하는 패턴을 본 적 있나요?", difficulty: "중급" },
    { id: 85, question: "캐릭터 장착 무기에 따라 스킬이 바뀌어야 할까요?", difficulty: "고급" },
    { id: 86, question: "몬스터 약점이 명확하게 표시되어야 할까요 유저가 찾아야 할까요?", difficulty: "중급" },
    { id: 87, question: "캐릭터 조합(파티 구성)이 강제되는 것에 대한 의견은?", difficulty: "중급" },
    { id: 88, question: "몬스터가 벽을 넘어 플레이어를 추격해야 할까요?", difficulty: "중급" },
    { id: 89, question: "캐릭터 대사가 전투 중 나오는 것이 방해가 될까요?", difficulty: "중급" },
    { id: 90, question: "보스 몬스터를 일반 몬스터로 재활용하는 것에 대한 의견은?", difficulty: "중급" },
    { id: 91, question: "캐릭터 일러스트와 인게임 모델의 괴리를 줄이는 방법은?", difficulty: "중급" },
    { id: 92, question: "몬스터 AI 난이도 옵션을 제공해야 할까요?", difficulty: "중급" },
    { id: 93, question: "캐릭터 모션 캡처 데이터를 활용한 경험이 있나요?", difficulty: "고급" },
    { id: 94, question: "몬스터 행동 패턴 설계 시 가장 어려운 점은?", difficulty: "중급" },
    { id: 95, question: "캐릭터 기획에서 가장 중요하게 생각하는 요소는?", difficulty: "고급" },
    { id: 96, question: "몬스터 AI 테스트는 어떤 방식으로 진행하나요?", difficulty: "고급" },
    { id: 97, question: "본인이 가장 좋아하는 게임 캐릭터는 누구인가요?", difficulty: "초급" },
    { id: 98, question: "가장 인상 깊었던 보스 몬스터와 그 이유는?", difficulty: "초급" },
    { id: 99, question: "캐릭터 및 몬스터 기획자의 필수 역량은 무엇인가요?", difficulty: "고급" },
    { id: 100, question: "미래의 캐릭터 기획은 AI가 대신할 수 있을까요?", difficulty: "고급" },
  ],

  레벨디자인: [
    {
      id: 1,
      question: "레벨 디자인을 시작할 때 공간(Topography)부터 짭니까, 시나리오(Flow)부터 짭니까?",
      difficulty: "중급",
    },
    { id: 2, question: "그레이박싱(Blockout) 단계에서 가장 중점적으로 검증해야 할 것은?", difficulty: "고급" },
    { id: 3, question: "플레이어의 시선을 유도하여 길을 잃지 않게 만드는(Guidance) 기법은?", difficulty: "중급" },
    { id: 4, question: "오픈월드와 선형적(Linear) 레벨 디자인의 가장 큰 기획적 차이는?", difficulty: "중급" },
    { id: 5, question: "엄폐물(Cover) 배치가 전투 난이도와 템포에 미치는 영향은?", difficulty: "중급" },
    {
      id: 6,
      question: "맵에서 유저가 지루함을 느끼지 않도록 긴장감의 강약(Pacing)을 조절하는 법은?",
      difficulty: "고급",
    },
    { id: 7, question: "랜드마크(Landmark)가 레벨 디자인에서 수행하는 기능 2가지는?", difficulty: "중급" },
    { id: 8, question: "수직적 구조(Verticality)를 활용했을 때 얻을 수 있는 전략적 재미는?", difficulty: "중급" },
    { id: 9, question: "퍼즐 요소와 전투 요소의 적절한 배합 비율은 어떻게 정하나요?", difficulty: "중급" },
    {
      id: 10,
      question: "유저가 의도치 않은 곳으로 맵을 이탈(Map out)하는 것을 자연스럽게 막는 법은?",
      difficulty: "중급",
    },
    { id: 11, question: "세이브 포인트(체크포인트)의 간격은 어떤 데이터를 근거로 설정하나요?", difficulty: "중급" },
    {
      id: 12,
      question: "몬스터 스폰 위치를 정할 때 '포위'와 '정면 승부'의 경험 차이를 어떻게 설계하나요?",
      difficulty: "고급",
    },
    {
      id: 13,
      question: "백트래킹(왔던 길 되돌아가기)을 시킬 때 유저가 지겹지 않게 만드는 장치는?",
      difficulty: "중급",
    },
    { id: 14, question: "PvP 맵에서 대칭형 구조와 비대칭형 구조의 밸런스 차이는?", difficulty: "고급" },
    { id: 15, question: "포트폴리오의 해당 레벨에서 '공간을 통한 스토리텔링'이 적용된 부분은?", difficulty: "고급" },
    { id: 16, question: "조명(Lighting)이 레벨의 동선 유도에 미치는 영향은?", difficulty: "중급" },
    { id: 17, question: "막다른 길(Dead End)에는 반드시 보상이 있어야 한다고 생각하나요?", difficulty: "중급" },
    { id: 18, question: "스나이퍼나 원거리 딜러가 너무 유리해지지 않도록 맵을 설계하는 방법은?", difficulty: "고급" },
    { id: 19, question: "레벨 디자인 시 최적화(Occlusion Culling 등)를 염두에 두고 배치하나요?", difficulty: "고급" },
    { id: 20, question: "맵의 규모(Scale)를 설정할 때 캐릭터 이동 속도를 어떻게 계산하나요?", difficulty: "고급" },
    { id: 21, question: "좁은 통로와 넓은 광장의 전투 경험 차이를 의도하고 배치하나요?", difficulty: "중급" },
    { id: 22, question: "낙사 구간(Falling)을 배치할 때 유저의 스트레스를 줄이는 안전장치는?", difficulty: "중급" },
    { id: 23, question: "레이싱이나 탈것이 있는 맵에서 속도감을 느끼게 하는 오브젝트 배치는?", difficulty: "중급" },
    { id: 24, question: "공포(Horror) 분위기를 조성하기 위한 폐쇄적인 공간 설계 팁은?", difficulty: "중급" },
    {
      id: 25,
      question: "특정 지역에서 '캠핑(Camping)' 플레이가 고착화될 때 맵을 어떻게 수정하나요?",
      difficulty: "고급",
    },
    { id: 26, question: "자원(HP 포션, 탄약 등) 배치 밀도가 난이도에 미치는 영향은?", difficulty: "중급" },
    {
      id: 27,
      question: "레벨 디자이너로서 아티스트(배경 모델러)와 협업할 때 가장 신경 쓰는 부분은?",
      difficulty: "중급",
    },
    { id: 28, question: "절차적 생성(Procedural Generation) 맵의 장점과 한계는 무엇일까요?", difficulty: "고급" },
    { id: 29, question: "테스트 플레이 중 유저들이 의도한 동선을 무시하고 '숏컷'을 찾아낸다면?", difficulty: "고급" },
    {
      id: 30,
      question: "언리얼 엔진이나 유니티 엔진의 지형 툴(Landscape/Terrain)을 다룰 줄 아나요?",
      difficulty: "고급",
    },
    // 뉘앙스 변형 및 상황 추가 (31-100)
    { id: 31, question: "레벨 디자인에서 공간과 시나리오 중 무엇이 더 중요한가요?", difficulty: "중급" },
    { id: 32, question: "그레이박싱에서 텍스처를 일부러 단순하게 두는 이유는?", difficulty: "중급" },
    { id: 33, question: "플레이어 시선 유도에서 색상과 조명 중 무엇이 더 효과적인가요?", difficulty: "중급" },
    { id: 34, question: "오픈월드에서 플레이어가 길을 잃지 않게 하는 방법은?", difficulty: "중급" },
    { id: 35, question: "엄폐물 높이가 게임플레이에 미치는 영향은?", difficulty: "중급" },
    { id: 36, question: "레벨 페이싱에서 긴장-이완-긴장 패턴이 효과적인가요?", difficulty: "중급" },
    { id: 37, question: "랜드마크를 시각적으로 돋보이게 만드는 방법은?", difficulty: "중급" },
    { id: 38, question: "수직 레벨 디자인에서 추락사 위험을 어떻게 조절하나요?", difficulty: "중급" },
    { id: 39, question: "퍼즐이 너무 어려워서 진행이 막히는 것을 방지하려면?", difficulty: "중급" },
    { id: 40, question: "보이지 않는 벽 대신 자연스러운 경계를 만드는 방법은?", difficulty: "중급" },
    { id: 41, question: "체크포인트가 너무 자주 나오면 긴장감이 떨어지나요?", difficulty: "중급" },
    { id: 42, question: "몬스터를 뒤에서 기습 배치하는 것이 불공정하게 느껴질 수 있나요?", difficulty: "중급" },
    { id: 43, question: "백트래킹 시 새로운 적이나 이벤트를 추가해야 할까요?", difficulty: "중급" },
    { id: 44, question: "PvP 맵에서 한쪽 팀이 유리한 위치를 선점하면 어떻게 밸런스를 맞추나요?", difficulty: "고급" },
    { id: 45, question: "환경 오브젝트를 통해 스토리를 전달한 사례가 있나요?", difficulty: "고급" },
    { id: 46, question: "어두운 맵에서 플레이어가 방향을 잃지 않게 하는 조명 배치는?", difficulty: "중급" },
    { id: 47, question: "막다른 길에 보상이 없으면 유저가 탐험을 안 하게 되나요?", difficulty: "중급" },
    { id: 48, question: "원거리 저격 위치를 막기 위한 맵 디자인 기법은?", difficulty: "고급" },
    { id: 49, question: "레벨 LOD(Level of Detail) 설정을 기획 단계에서 고려하나요?", difficulty: "고급" },
    { id: 50, question: "캐릭터 키 높이를 기준으로 문이나 계단을 설계하나요?", difficulty: "중급" },
    { id: 51, question: "통로 전투와 광장 전투를 반복 배치하는 이유는?", difficulty: "중급" },
    { id: 52, question: "낙사 후 부활 위치를 어디로 설정해야 스트레스가 적을까요?", difficulty: "중급" },
    { id: 53, question: "속도감 연출을 위해 배경 오브젝트 간격을 어떻게 조절하나요?", difficulty: "중급" },
    { id: 54, question: "공포 게임에서 열린 공간과 닫힌 공간의 배치 비율은?", difficulty: "중급" },
    { id: 55, question: "캠핑을 막기 위해 타이머나 이벤트를 강제해야 할까요?", difficulty: "고급" },
    { id: 56, question: "자원 배치가 너무 많으면 난이도가 너무 쉬워지나요?", difficulty: "중급" },
    { id: 57, question: "배경 아티스트가 기획 의도를 무시하고 예쁘게만 만들 때 대응은?", difficulty: "중급" },
    { id: 58, question: "절차 생성 맵에서 플레이어가 막히는 경우를 방지하려면?", difficulty: "고급" },
    { id: 59, question: "의도하지 않은 숏컷이 발견되면 막아야 할까요 허용해야 할까요?", difficulty: "고급" },
    { id: 60, question: "레벨 에디터 툴을 직접 만들어 본 경험이 있나요?", difficulty: "고급" },
    { id: 61, question: "레벨 디자인에서 황금비율이나 룰 오브 서드를 활용하나요?", difficulty: "고급" },
    { id: 62, question: "멀티플레이 맵과 싱글플레이 맵의 설계 차이는?", difficulty: "중급" },
    { id: 63, question: "맵 경계를 산이나 강으로 자연스럽게 막는 방법은?", difficulty: "초급" },
    { id: 64, question: "레벨 내 히든 공간(숨겨진 방)을 어떻게 암시하나요?", difficulty: "중급" },
    { id: 65, question: "레벨의 시작점과 끝점을 시각적으로 구분하는 방법은?", difficulty: "중급" },
    { id: 66, question: "맵 미니맵 디자인과 실제 레벨 구조가 일치해야 할까요?", difficulty: "중급" },
    { id: 67, question: "웨이포인트 시스템이 레벨 디자인의 창의성을 해칠 수 있나요?", difficulty: "중급" },
    { id: 68, question: "파쿠르 레벨 디자인에서 실패 시 재시작 위치는 어디가 좋을까요?", difficulty: "중급" },
    { id: 69, question: "레벨 내 NPC 배치 위치가 플레이어 동선에 미치는 영향은?", difficulty: "중급" },
    { id: 70, question: "탐험 보상으로 스토리 요소를 주는 것이 효과적인가요?", difficulty: "중급" },
    { id: 71, question: "레벨의 테마(숲, 동굴, 도시 등)가 게임플레이에 영향을 줘야 할까요?", difficulty: "중급" },
    { id: 72, question: "레벨 길이(플레이 타임)를 어떻게 예측하고 조절하나요?", difficulty: "중급" },
    { id: 73, question: "보스룸 입구에 세이브 포인트를 반드시 배치해야 할까요?", difficulty: "중급" },
    { id: 74, question: "레벨 내 상호작용 오브젝트의 적정 개수는?", difficulty: "중급" },
    { id: 75, question: "플랫포머 게임에서 점프 거리 계산을 어떻게 하나요?", difficulty: "고급" },
    { id: 76, question: "레벨 반복 플레이를 위한 랜덤 요소 배치 전략은?", difficulty: "고급" },
    { id: 77, question: "레벨 디자인 프로토타입을 몇 번이나 수정하나요?", difficulty: "중급" },
    { id: 78, question: "화이트박스에서 그레이박스로 넘어가는 기준은?", difficulty: "고급" },
    { id: 79, question: "레벨 디자인 문서에 반드시 포함되어야 할 항목은?", difficulty: "중급" },
    { id: 80, question: "플레이 테스트에서 가장 자주 발견되는 레벨 디자인 문제는?", difficulty: "고급" },
    { id: 81, question: "레벨 스크립팅과 레벨 디자인의 경계는 어디인가요?", difficulty: "고급" },
    { id: 82, question: "레벨 내 컷신 발동 위치를 어떻게 정하나요?", difficulty: "중급" },
    { id: 83, question: "오픈월드 맵에서 플레이어가 갈 곳을 찾지 못할 때 힌트를 줘야 할까요?", difficulty: "중급" },
    { id: 84, question: "레벨 디자인에서 대칭 구조의 장점과 단점은?", difficulty: "중급" },
    { id: 85, question: "레벨의 색상 팔레트가 플레이어 감정에 미치는 영향은?", difficulty: "중급" },
    { id: 86, question: "날씨 변화가 레벨 분위기에 주는 효과는?", difficulty: "초급" },
    { id: 87, question: "동적 오브젝트(파괴 가능한 벽 등) 배치 시 주의사항은?", difficulty: "중급" },
    { id: 88, question: "레벨 내 적 밀도를 구역별로 다르게 가져가는 이유는?", difficulty: "중급" },
    { id: 89, question: "레벨 아트와 레벨 디자인 중 어느 것을 먼저 완성하나요?", difficulty: "중급" },
    { id: 90, question: "플레이어가 벽을 타고 올라가는 것을 허용해야 할까요?", difficulty: "중급" },
    { id: 91, question: "레벨 모듈화 시스템을 사용해 본 경험이 있나요?", difficulty: "고급" },
    { id: 92, question: "언리얼과 유니티 중 레벨 디자인에 어느 엔진이 더 편한가요?", difficulty: "초급" },
    { id: 93, question: "레벨 디자인에서 가장 어려운 부분은 무엇인가요?", difficulty: "중급" },
    { id: 94, question: "레벨 디자이너에게 가장 필요한 능력은 무엇이라고 생각하나요?", difficulty: "고급" },
    { id: 95, question: "본인이 가장 좋아하는 게임 레벨은 무엇인가요?", difficulty: "초급" },
    { id: 96, question: "레벨 디자인 참고 자료는 어디서 얻나요?", difficulty: "초급" },
    { id: 97, question: "레벨 디자인 포트폴리오 제작 시 주의사항은?", difficulty: "중급" },
    { id: 98, question: "VR 레벨 디자인과 일반 레벨 디자인의 차이는?", difficulty: "고급" },
    { id: 99, question: "레벨 디자인 트렌드는 어떻게 변화하고 있나요?", difficulty: "중급" },
    { id: 100, question: "미래의 레벨 디자인은 AI가 자동 생성할 수 있을까요?", difficulty: "고급" },
  ],
}
